remote_theme: jekyll/minima

url: "https://shiromatz.com"
title: Shiro Matsumoto
subtitle: Data Science Consultant with 25+ Years of Experience
lang: en

# Analytics
google_analytics: G-S8JJLWE1JX

analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : "G-S8JJLWE1JX"

plugins:
- jekyll-analytics
- jekyll-remote-theme
- jekyll-sitemap
